# Generated by Django 4.2.27 on 2025-12-20 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the destination', max_length=200)),
                ('location', models.CharField(help_text='Location/Country of the destination', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the destination')),
                ('image_url', models.CharField(help_text='URL or path to destination image', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, help_text='Starting price for tour package (in PHP)', max_digits=10)),
                ('duration', models.CharField(help_text="Duration of the tour (e.g., '3 Days 2 Nights')", max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this destination is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Package title', max_length=200)),
                ('package_type', models.CharField(choices=[('domestic', 'Domestic Tour'), ('international', 'International Tour'), ('adventure', 'Adventure Tour'), ('beach', 'Beach Getaway'), ('cultural', 'Cultural Tour'), ('custom', 'Custom Package')], default='domestic', help_text='Type of travel package', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the package')),
                ('inclusions', models.TextField(help_text="What's included in the package")),
                ('exclusions', models.TextField(blank=True, help_text="What's not included in the package")),
                ('price', models.DecimalField(decimal_places=2, help_text='Package price (in PHP)', max_digits=10)),
                ('max_guests', models.PositiveIntegerField(default=10, help_text='Maximum number of guests')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the package is available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(help_text='Related destination', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Travel Package',
                'verbose_name_plural': 'Travel Packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
